### ISSUE TITLE
Outdated css?

### ISSUE THREAD

**Issue by danielegobbetti** [SASAbus/SASA-Bus-Stop#3]
HI,

yesterday at the [LUGBZ workshop](http://lists.lugbz.org/pipermail/lugbz-list/2015-October/022686.html) we have seen that the color scheme of the display was changed to a light theme, the master version in the repository is still using the old dark scheme.

**Comment by bertolla** [comment]
Hi,
The black version is still the orignal so it's not outdated. We just created an inverted version for the bus station, where the visibility during the day was much better.

You can find the inverted version on branch https://github.com/SASAbus/SASA-Bus-Stop/tree/inverted

It's up to SASA to decide if the inverted version is going to become the original and if they want to merge the 2 versions.

**Comment by markuswindegger** [comment]
We have created the branch inverted, as this is a test, if the light scheme is more visible in sunny days. It will be merged to the master if we decide what theme is better solving the problem of visibility.

**Comment by danielegobbetti** [comment]
Understood, sorry for the noise :)

**Comment by markuswindegger** [comment]
No problem, comments allways appreciated! ;-)

Am 7. Oktober 2015 11:13:04 MESZ, schrieb Daniele Gobbetti <notifications@github.com>:
>Understood, sorry for the noise :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SASAbus/SASA-Bus-Stop/issues/3#issuecomment-146127844

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
